project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.ipynb
      - text: Slides
        href: slides/slides.ipynb
bibliography: reference.bib

format:
  html:
    embed-resources: true
    code-fold: true
    theme:
      - cosmo
    toc: true